# Generated by Django 2.1.5 on 2020-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='cpu_frequency',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='processor_cores',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram_size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='computer',
            name='ssd_capacity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
