# Generated by Django 2.1.5 on 2020-04-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_auto_20200428_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(default='', height_field=100, upload_to='static/static_dirs/images/', width_field=100),
        ),
    ]
