# Generated by Django 2.1.5 on 2020-04-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0007_auto_20200430_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='image',
        ),
    ]
