# Generated by Django 2.1.5 on 2020-04-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0008_remove_computer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='computer value',
            new_name='name',
        ),
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(default='', upload_to='static/static_dirs/images/'),
        ),
    ]
