# Generated by Django 2.1.5 on 2020-04-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0009_auto_20200430_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
