# Generated by Django 2.1.5 on 2020-05-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0011_auto_20200430_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(upload_to='computers/'),
        ),
    ]
