# Generated by Django 2.1.5 on 2020-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0012_auto_20200504_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
